version: "3.8"

services:
  booking-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - Booking.Api/.env
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./Booking.Api/appsettings.json:/app/appsettings.json
      - ./Booking.Api/appsettings.Development.json:/app/appsettings.Development.json
    restart: unless-stopped
