version: '3.8'

services:
  booking-api:
    build:
      context: .
      dockerfile: Booking.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    volumes:
      - booking-api-data:/app/data
    depends_on:
      - postgres
    networks:
      - booking-network

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=bookingdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - booking-network

volumes:
  booking-api-data:
  postgres-data:

networks:
  booking-network:
    driver: bridge